# Generated by Django 5.0.4 on 2024-06-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0004_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('user', 'title')},
        ),
    ]
